// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UploadPurchaseOrder.Data;

namespace UploadPurchaseOrder.Migrations
{
    [DbContext(typeof(PurchaseOrderContext))]
    partial class PurchaseOrderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("UploadPurchaseOrder.Models.PurchaseOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("buyerCityStateZip")
                        .HasColumnType("TEXT");

                    b.Property<string>("buyerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("buyerPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("buyerStreetAddress")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("fullTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("orderNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("purchaseOrderPDF")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("shipping")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("subtotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("tax")
                        .HasColumnType("TEXT");

                    b.Property<string>("vendorCityStateZip")
                        .HasColumnType("TEXT");

                    b.Property<string>("vendorName")
                        .HasColumnType("TEXT");

                    b.Property<string>("vendorPhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("vendorStreetAddress")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("PurchaseOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
